import { existsSync, readFileSync, writeFileSync, mkdirSync, createWriteStream } from "node:fs";
import { join } from "node:path";
import { statSync, readFileSync as readFile } from "node:fs";
import { createHash } from "node:crypto";
import archiver from "archiver";
const required=["public/index.html","public/admin/index.html","api/health.js","server/index.js"];
for(const file of required)if(!existsSync(file))throw new Error(`Missing required deployment file: ${file}`);
const clientId=String(process.env.GOOGLE_CLIENT_ID||"__GOOGLE_CLIENT_ID__").trim();
writeFileSync("public/config.js",`window.TDT_CONFIG=${JSON.stringify({googleClientId:clientId})};\n`);
const base=String(process.env.PUBLIC_BASE_URL||"https://tdt-vercel-control.vercel.app").replace(/\/$/,"");
const releaseDir=join("public","extension","releases");mkdirSync(releaseDir,{recursive:true});
const sourceDir=join("extension-src");
const manifestPath=join(sourceDir,"manifest.json");
const manifest=JSON.parse(readFileSync(manifestPath,"utf8"));manifest.version="4.0.0";writeFileSync(manifestPath,JSON.stringify(manifest,null,2)+"\n");
const configPath=join(sourceDir,"remote_config.js");
writeFileSync(configPath,`"use strict";globalThis.TDT_REMOTE_CONFIG=Object.freeze(${JSON.stringify({enabled:true,serverUrl:base,projectKey:String(process.env.TDT_PROJECT_KEY||"tiktok-tai-dep-trai"),expectedExtensionId:String(process.env.TDT_EXTENSION_ID||"cpndheccadlhkiogcfdhagomiadbaogn"),heartbeatMinutes:1,requestTimeoutMs:8000,leaseSeconds:90,failMode:"closed",privateUpdates:{enabled:true,manifestUrl:`${base}/api/v1/extension/update-manifest`,manifestFallbackUrls:[`${base}/extension/releases/latest.json`],releasePageUrl:`${base}/extension/`,checkMinutes:60,autoDownload:true}})});\n`);
const zipPath=join(releaseDir,"TikTok_Tai_Dep_Trai_v4.0.0.zip");
await new Promise((resolve,reject)=>{const output=createWriteStream(zipPath);const archive=archiver("zip",{zlib:{level:9}});output.on("close",resolve);archive.on("error",reject);archive.pipe(output);archive.directory(sourceDir,false);archive.finalize();});
const bytes=readFile(zipPath);const latest={version:"4.0.0",downloadUrl:`${base}/api/v1/extension/download?version=4.0.0`,releasePageUrl:`${base}/extension/`,releaseNotes:"Vercel-only: API, Google Sign-In, database, storage và cập nhật extension chạy trên Vercel.",publishedAt:new Date().toISOString(),sha256:createHash("sha256").update(bytes).digest("hex"),mandatory:true,filename:"TikTok_Tai_Dep_Trai_v4.0.0.zip",sizeBytes:bytes.length};writeFileSync(join(releaseDir,"latest.json"),JSON.stringify(latest,null,2)+"\n");
writeFileSync("public/extension/updates.xml",`<?xml version="1.0" encoding="UTF-8"?>\n<gupdate xmlns="http://www.google.com/update2/response" protocol="2.0"><app appid="${String(process.env.TDT_EXTENSION_ID||"cpndheccadlhkiogcfdhagomiadbaogn")}"><updatecheck codebase="${base}/extension/releases/TikTok_Tai_Dep_Trai_v4.0.0.zip" version="4.0.0" /></app></gupdate>\n`);
console.log(`Vercel-only build OK: ${required.length} required files present; extension packaged at ${zipPath}.`);
